before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - node_modules/buster/bin/buster-server &
  - sleep 5
  - google-chrome http://localhost:1111/capture 2> /dev/null &
  - sleep 5


script:
  - "npm test"

language: node_js

node_js:
  - 4.2.1
